#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$ROOT_DIR/build_maca2}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
BUILD_TARGET="${BUILD_TARGET:-unittest}"
HIPRT_RUNTIME_KERNEL_CACHE="${HIPRT_RUNTIME_KERNEL_CACHE:-OFF}"
HIPRT_ENABLE_BAKE_KERNEL="${HIPRT_ENABLE_BAKE_KERNEL:-OFF}"
HIPRT_ENABLE_BITCODE="${HIPRT_ENABLE_BITCODE:-OFF}"
HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL="${HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL:-OFF}"

: "${MACA_PATH:=/opt/maca}"
: "${CUCC_PATH:=$MACA_PATH/tools/cu-bridge}"
: "${CUDA_PATH:=$CUCC_PATH}"

export MACA_PATH
export CUCC_PATH
export CUDA_PATH
export PATH="${CUCC_PATH}/tools:${CUCC_PATH}/bin:${PATH}"
export CUCC_CMAKE_ENTRY="${CUCC_CMAKE_ENTRY:-2}"
export LIBRARY_PATH="${CUCC_PATH}/lib:/opt/mxdriver/lib:${LIBRARY_PATH:-}"

cmake_maca -S "$ROOT_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
	-DHIPRT_ENABLE_RUNTIME_KERNEL_CACHE="$HIPRT_RUNTIME_KERNEL_CACHE" \
	-DHIPRT_ENABLE_BAKE_KERNEL="$HIPRT_ENABLE_BAKE_KERNEL" \
	-DHIPRT_ENABLE_BITCODE="$HIPRT_ENABLE_BITCODE" \
	-DHIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL="$HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL"
pushd "$BUILD_DIR" >/dev/null
make_maca -j"${BUILD_JOBS:-4}" "$BUILD_TARGET"
if [[ "$HIPRT_ENABLE_BITCODE" == "ON" ]]; then
	make_maca -j"${BUILD_JOBS:-4}" hiprt_compile_bitcode
fi
if [[ "$HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL" == "ON" ]]; then
	make_maca -j"${BUILD_JOBS:-4}" hiprt_precompile_trace_kernels
fi
popd >/dev/null
