#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$ROOT_DIR/build}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
CUDA_ARCHITECTURES="${CUDA_ARCHITECTURES:-}"
BUILD_TESTS="${BUILD_TESTS:-ON}"
GENERATOR="${GENERATOR:-Ninja}"
CCACHE_PROGRAM="${CCACHE_PROGRAM:-$(command -v ccache || true)}"
MOLD_PROGRAM="${MOLD_PROGRAM:-$(command -v mold || true)}"
HIPRT_ENABLE_RUNTIME_KERNEL_CACHE="${HIPRT_ENABLE_RUNTIME_KERNEL_CACHE:-}"
HIPRT_ENABLE_BAKE_KERNEL="${HIPRT_ENABLE_BAKE_KERNEL:-}"
HIPRT_ENABLE_BITCODE="${HIPRT_ENABLE_BITCODE:-}"
HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL="${HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL:-}"

cmake_args=(
  -S "$ROOT_DIR"
  -B "$BUILD_DIR"
  -G "$GENERATOR"
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
)

if [[ -n "$CUDA_ARCHITECTURES" ]]; then
  cmake_args+=(-DCMAKE_CUDA_ARCHITECTURES="$CUDA_ARCHITECTURES")
fi

if [[ "$BUILD_TESTS" == "OFF" ]]; then
  cmake_args+=(-DNO_UNITTEST=ON)
fi

if [[ -n "$HIPRT_ENABLE_RUNTIME_KERNEL_CACHE" ]]; then
  cmake_args+=(-DHIPRT_ENABLE_RUNTIME_KERNEL_CACHE="$HIPRT_ENABLE_RUNTIME_KERNEL_CACHE")
fi

if [[ -n "$HIPRT_ENABLE_BAKE_KERNEL" ]]; then
  cmake_args+=(-DHIPRT_ENABLE_BAKE_KERNEL="$HIPRT_ENABLE_BAKE_KERNEL")
fi

if [[ -n "$HIPRT_ENABLE_BITCODE" ]]; then
  cmake_args+=(-DHIPRT_ENABLE_BITCODE="$HIPRT_ENABLE_BITCODE")
fi

if [[ -n "$HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL" ]]; then
  cmake_args+=(-DHIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL="$HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL")
fi

if [[ -n "$CCACHE_PROGRAM" ]]; then
  cmake_args+=(
    -DCMAKE_C_COMPILER_LAUNCHER="$CCACHE_PROGRAM"
    -DCMAKE_CXX_COMPILER_LAUNCHER="$CCACHE_PROGRAM"
    -DCMAKE_CUDA_COMPILER_LAUNCHER="$CCACHE_PROGRAM"
  )
fi

if [[ -n "$MOLD_PROGRAM" ]]; then
  MOLD_DIR="$(dirname "$MOLD_PROGRAM")"
  cmake_args+=(
    -DCMAKE_EXE_LINKER_FLAGS="-B$MOLD_DIR"
    -DCMAKE_SHARED_LINKER_FLAGS="-B$MOLD_DIR"
  )
fi

cmake "${cmake_args[@]}"
cmake --build "$BUILD_DIR" --config "$BUILD_TYPE" -j

if [[ "${HIPRT_ENABLE_BITCODE:-}" == "ON" ]]; then
  cmake --build "$BUILD_DIR" --config "$BUILD_TYPE" --target hiprt_compile_bitcode -j
fi

if [[ "${HIPRT_ENABLE_PRECOMPILED_TRACE_KERNEL:-}" == "ON" ]]; then
  cmake --build "$BUILD_DIR" --config "$BUILD_TYPE" --target hiprt_precompile_trace_kernels -j
fi
