//
// Copyright (c) 2021-2024 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
#pragma once

#include <cuda_runtime_api.h>
#include <cuda.h>
#include <cuda_profiler_api.h>
#include <nvrtc.h>


// This part allows Orochi.h to be included by device kernel code and expose
// a CUDA-oriented API surface without depending on separate loader helpers.
// TODO: make this list exhaustive by auto-generating it with Orochi Summoner.

#define OROAPI HIPAPI
#define ORO_CB HIP_CB


#pragma region OROCHI_SUMMONER_REGION_cudachi_h

/////
///// THIS REGION HAS BEEN AUTOMATICALLY GENERATED BY OROCHI SUMMONER.
///// Manual modification of this region is not recommended.
/////



///// END REGION: OROCHI_SUMMONER_REGION_cudachi_h
///// (region automatically generated by Orochi Summoner)
#pragma endregion





enum cudaApi
{
	ORO_API_AUTOMATIC = 1<<0,
	ORO_API_HIPDRIVER = 1 << 1,
	ORO_API_HIPRTC = 1 << 2,
	ORO_API_HIP = ORO_API_HIPDRIVER | ORO_API_HIPRTC,
	ORO_API_CUDADRIVER = 1 << 3,
	ORO_API_CUDARTC = 1 << 4,
	ORO_API_CUDA = ORO_API_CUDADRIVER | ORO_API_CUDARTC,
};


typedef unsigned int cudaU32;

// cudaCtx represent a special struct override by Orochi.
// It doesn't represent the original 'hipCtx_t'
typedef struct iCUcontext* cudaCtx;


#define ORO_LAUNCH_PARAM_BUFFER_POINTER HIP_LAUNCH_PARAM_BUFFER_POINTER
#define ORO_LAUNCH_PARAM_BUFFER_SIZE HIP_LAUNCH_PARAM_BUFFER_SIZE
#define ORO_EXTERNAL_MEMORY_DEDICATED 0x1
#define ORO_TRSF_READ_AS_INTEGER 0x01


typedef enum PPshared_carveout_enum {
	ORO_SHAREDMEM_CARVEOUT_DEFAULT,
	ORO_SHAREDMEM_CARVEOUT_MAX_SHARED = 100,
	ORO_SHAREDMEM_CARVEOUT_MAX_L1 = 0,
} PPshared_carveout;


typedef enum OROmem_advise_enum {
	ORO_MEM_ADVISE_SET_READ_MOSTLY = 1,
	ORO_MEM_ADVISE_UNSET_READ_MOSTLY = 2,
	ORO_MEM_ADVISE_SET_PREFERRED_LOCATION = 3,
	ORO_MEM_ADVISE_UNSET_PREFERRED_LOCATION = 4,
	ORO_MEM_ADVISE_SET_ACCESSED_BY = 5,
	ORO_MEM_ADVISE_UNSET_ACCESSED_BY = 6,
} PPmem_advise;

typedef enum OROmem_range_attribute_enum {
	ORO_MEM_RANGE_ATTRIBUTE_READ_MOSTLY = 1,
	ORO_MEM_RANGE_ATTRIBUTE_PREFERRED_LOCATION = 2,
	ORO_MEM_RANGE_ATTRIBUTE_ACCESSED_BY = 3,
	ORO_MEM_RANGE_ATTRIBUTE_LAST_PREFETCH_LOCATION = 4,
} PPmem_range_attribute;


enum {
	ORO_SUCCESS = 0,
	ORO_ERROR_OPEN_FAILED = -1,
	ORO_ERROR_ATEXIT_FAILED = -2,
	ORO_ERROR_OLD_DRIVER = -3,
};


//
// Functions of Orochi that are not part of the Orochi Summoner auto-generated source code.
// They are either functions specific to Orochi ( not part of Hip/Cuda API ),  or because they are too complex to be automatically generated by Orochi Summoner.
// Any function declared here will be detected by Orochi Summoner and not auto-generated.
//

// customPaths_** are optional parameters
//   They be used to overide the default values defined in Orochi.
//   It's a list of C-strings. This list must have a NULL as last element.
//   The order of the elements matters: the first library file to exist will be the one loaded.
//   Examples, for Hip on Windows:
//     customPaths_Hip[]    = {"amdhip64_6.dll", "amdhip64.dll", NULL};
//     customPaths_Hiprtc[] = {"hiprtc0600.dll", "hiprtc0507.dll", NULL};
//     Note that those lists are non-correlated, meaning Orochi can take for example the second element of customPaths_Hip and the first element of customPaths_Hiprtc.

