//
// Copyright (c) 2021-2024 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//



#include <Orochi/Orochi.h>
#include <stdio.h>
#include <string.h>
#include <unordered_map>
#include <mutex>





// this namespace will be for encapsulating all the files related to CUDA
// we need to make that into a workspace espacially because of the files from HIP SDK:  nvidia_hip_runtime_api.h  /  nvidia_hiprtc.h.  that creates new definitions of hip**** functions


std::unordered_map<void*, cudaCtx> s_cudaCtxs;
static std::mutex mtx;
thread_local static cudaApi s_api = ORO_API_HIP;
static cudaU32 s_loadedApis = 0;

struct iCUcontext
{
public:

	iCUcontext()
	{
		m_ptr = nullptr;
		m_storage = 0;
	}

	void* m_ptr;
private:
	cudaU32 m_storage;

public:
	cudaApi getApi() const { return (cudaApi)m_storage; }
	void setApi( cudaApi api ) { m_storage = api; }
};

struct icudaDevice
{
private:
	cudaU32 m_api : 4;
	cudaU32 m_deviceIdx : 16;

public:
	icudaDevice( int src = 0)
	{
		((int*)this)[0] = src;
	}

	cudaApi getApi() const { return (cudaApi)m_api; }
	void setApi(cudaApi api) { m_api = api; }
	int getDevice() const { return m_deviceIdx; }
	void setDevice( int d ) { m_deviceIdx = d; }
};

///// END REGION: OROCHI_SUMMONER_REGION_cudachi_cpp_switch
///// (region automatically generated by Orochi Summoner)
#pragma endregion